config/routes.rb
Rails.application.routes.draw do
  root 'champions#index'
  resources :champions
  resources :skills
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
  has_many :skills, dependent: :destroy
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :champion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController

  def index
    @champions = Champion.all
  end

  def show
    @champion = Champion.find(params[:id])
  end

  def new
    @champion = Champion.new
  end

  def edit
    @champion = Champion.find(params[:id])
  end

  def create
    @champion = Champion.new(champion_params)
    # you can use a conditional here to redirect_to a successfully created item
    # or render the form again with the errors associated with saving the object to the db
    @champion.save
    redirect_to champion_path(@champion)
  end

  def update
    @champion = Champion.find(params[:id])
    @champion.update(champion_params)
    @champion.save # update calls save, line is unneccessary
    redirect_to champion_path(@champion)
  end


  private
  def champion_params
    params.require(:champion).permit(:name, :img_url, :video_url, :description)
  end


end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
    # champion_names makes more sense
    @champion_champion = Champion.all.map{ |champion| champion.name}
  end

  def create
    @skill = Skill.new(skill_params)
    puts "=========================#{params[:skill][:champion]}"
    @skill.champion = Champion.find_by(name: params[:skill][:champion])
    @skill.save
    redirect_to skill_path(@skill)
  end

  def update
    @skill = Skill.find(params[:id])
    @skill.update(skill_params)
    redirect_to skill_path(@skill)
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to champions_path
  end

  private
  def skill_params
    params.require(:skill).permit(:name, :img_url, :video_url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/champions/edit.html.erb
<h2>Edit Champion</h2>
<%= form_for @champion do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :Image %>
 <%= f.text_field :img_url %>

 <%= f.submit %>
 <% end %>

<!-- unlinked in your application; link it from champsion show view maybe.  -->

app/views/champions/index.html.erb
<h1>The Champions</h1>
<% @champions.each do |champion| %>
<div class="champion">
  <h2><%=link_to champion.name, champion_path(champion)%></h2>
  <img src="<%= champion.img_url %>"/>
</div>
<% end %>

app/views/champions/new.html.erb
<h2>New Champion</h2>

<%= form_for @champion do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :Image %>
 <%= f.text_field :img_url %>


 <%= f.submit %>
<% end %>

app/views/champions/show.html.erb
<h1><%= @champion.name %></h1>
<img src="<%= @champion.img_url %>">
<% @champion.skills.each do |skill| %>
<div class="skill">

   <h3><%= skill.name %></h3>
   <%= skill.description %><br>
   <img src="<%= skill.img_url %>">
   <a href="<%= skill.video_url%>"><br>Show Video skill</a>

   <h3><%= link_to "Edit Skill", edit_skill_path(skill) %></h3>



</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>League of Legends DB</title>
   <%= csrf_meta_tags %>

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

 <body>

   <h2><%= link_to "View Champions", champions_path %> | <%= link_to "New Champion", new_champion_path %> | <%= link_to "New Skill", new_skill_path %></h2>
   <!-- Could render flash errors, alerts, and notices here -->
   <%= yield %>
 </body>
</html>

app/views/skills/edit.html.erb
<h2>Edit Skill</h2>
<%= form_for @skill do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :Image %>
 <%= f.text_field :img_url %>

 <%= f.label :Video %>
 <%= f.text_field :video_url %>

 <%= f.label :description %>
 <%= f.text_field :description %>

 <%= f.submit %>

 <p><%= link_to 'Delete Skill', @skill,
           method: :delete,
           class: "delete",
           data: { confirm: 'Deleted!' } %></p>

 <% end %>

app/views/skills/index.html.erb
<h1>The Skills</h1>
<% @skills.each do |skill| %>
<div>
 <h2><%= link_to skill.name, skill_path(skill) %> - <%= Champion.find(skill.champion_id).name %></h2>

<% end %>
</div>

app/views/skills/new.html.erb
<h2>New Skill</h2>

<%= form_for @skill do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :Image %>
 <%= f.text_field :img_url %>

 <%= f.label :Video %>
 <%= f.text_field :video_url %>

 <%= f.label :description %>
 <%= f.text_field :description %>

 <%= f.select(:champion, options_for_select(@champion_champion))%>

 <%= f.submit %>
<% end %>

app/views/skills/show.html.erb
<h2><%= link_to "Champions", champions_path %></h2>

<h2><%= @skill.name %></h2>
<img src="<%= @skill.img_url %>">